# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 21:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import memo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время создания')),
                ('uuid', models.CharField(default=memo.models.uuid_defaults, max_length=36)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo.CategoryMemo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=255)),
            ],
        ),
    ]
