# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import memo.models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='memo',
            name='uuid',
            field=models.CharField(default=memo.models.uuid_defaults, max_length=36, unique=True),
        ),
    ]
